pipeline{
agent none
stages {

stage('clonning-repository-on-custom-directory') {
   agent {
   label 'built-in'
   }
 steps {
  dir('/mnt/qa-playbook') {
   sh 'rm -rf *'
   checkout scm
  }
 }
}

stage('playbook-run-for-qa-instances') {
  agent { 
    label 'built-in'
    }
    steps {
      dir('/mnt/qa-playbook/qa-project') {
       sh 'ansible-playbook master.yaml'
        }
      }
    }

 }
}
